IcySon55/Kuriimu

- Kuriimu/Common.cs
- Kuriimu/ExtensionSelect.cs
- KuriimuContract/PluginLoader.cs
This is just a few minor refactoring changes.
Feel free to review and cherry-pick at your leisure.
> Refactoring

- KuriimuContract/ListItem.cs
Reimplemented IComparable in ListItem
> Reimplemented IComparable in ListItem

- Kuriimu/Editor.cs
- KuriimuContract/PluginLoader.cs
Reverted LoadPlugins and attempted to make SelectFileAdapter easier to read
> Reverted LoadPlugins and simplified SelectFileAdapter

- KuriimuContract/CommonCompression.cs
- KuriimuContract/ImageCommon.cs
- Added CommonCompression.c including Huffman, LZSS, RLE compression
- Updated ImageCommon.cs
> Added CommonCompression

- game_zelda_a_link_between_worlds/Handler.cs
- game_zelda_a_link_between_worlds/Settings.Designer.cs
- game_zelda_a_link_between_worlds/Settings.cs
- game_zelda_a_link_between_worlds/Settings.resx
- game_zelda_a_link_between_worlds/game_zelda_a_link_between_worlds.csproj
PlayerName editing for ALBW. Max of 10 characters, as in the game.
> Handler settings support for ALBW

- game_zelda_a_link_between_worlds/Handler.cs
- game_zelda_a_link_between_worlds/Properties/Resources.Designer.cs
- game_zelda_a_link_between_worlds/Properties/Resources.resx
- game_zelda_a_link_between_worlds/game_zelda_a_link_between_worlds.csproj
- game_zelda_a_link_between_worlds/resources/item.txt
- game_zelda_a_link_between_worlds/resources/location.txt
- game_zelda_a_link_between_worlds/resources/npc.txt
+ Add cyan color control code
+ Include item, location and NPC names
~ Fix padding control code
> ALBW update + bugfix

- image_bclyt/BCLYT.cs
- image_bclyt/BclytSupport.cs
Supports Window, Pane and Bound
> First valid graphic output

- game_time_travelers/Handler.cs
- image_bclyt/BCLYT.cs
- image_bclyt/BclytSupport.cs
- image_bclyt/image_bclyt.csproj
Added textbox support
correct alignment
> Added textboxes

- file_tt_bin/TTBinAdapter.cs
- image_xi/XI.cs
Leaved unused code in TTBinAdapter
> Fixed a bug in TTBinAdapter

- archive_ctpk/CTPK.cs
- archive_ctpk/CtpkManager.cs
- archive_ctpk/CtpkSupport.cs
- archive_nus3bank/NUS3.cs
Added ZLib compression to NUS3 Save;
Adjust CTPK to handle multiple files in archive;
> Various changes

- Cetera/Archive/DARC.cs
- archive_cgrp/CGRP.cs
- archive_cgrp/CgrpManager.cs
- archive_cgrp/CgrpSupport.cs
- archive_ctpk/CTPK.cs
- archive_ctpk/CtpkManager.cs
- archive_darc/DarcManager.cs
- archive_fa/FA.cs
- archive_fa/FaManager.cs
- Replaced some filename inputs to Stream inputs;
> Added CGRP Save function;

- KuriimuContract/AES/AesEngine.cs
- KuriimuContract/UI/Encryption.cs
changed extension for decrypted files;
throw bootrom and n3ds_keystores in bin/ folder aside plugins/ folder;
> changed AESEngine to get bootrom as optional files;

- archive_fnt/FntManager.cs
- text_mbm/MBM.cs
Give right control codes in MBM;
> Put Fnt Identify in try-catch-Block;

- image_ctxb/CTXB.cs
- image_ctxb/CtxbAdapter.cs
> Patched CTXB to support multi-image;

- src/Cetera/Image/Common.cs
- src/archive/archive_level5/ARC0.cs
- src/archive/archive_level5/ARCV.cs
- src/archive/archive_level5/Arc0Manager.cs
- src/archive/archive_level5/ArcvSupport.cs
- src/archive/archive_level5/B123.cs
- src/archive/archive_level5/B123Support.cs
- src/archive/archive_level5/PCK.cs
- src/image/image_nintendo/CTPK.cs
- src/image/image_nintendo/CtpkAdapter.cs
- src/image/image_nintendo/CtpkSupport.cs
Revised ARCV Load/Save;
Revised B123 Load/Save;
Revised CTPK Load/Save;
Added GetBitDepth() to Cetera.Image to get bitDepth of supported imageFormats;
> Various updates

- src/CeteraDS/CeteraDS.csproj
- src/CeteraDS/Image/Common.cs
- src/image/image_nintendo/CHNKTEX.cs
- src/image/image_nintendo/ChnkTexAdapter.cs
- src/image/image_nintendo/ChnkTexSupport.cs
- src/image/image_nintendo/image_nintendo.csproj
Added option to set a transparent color in CeteraDS.Image;
Rewrote CHNK Load to use CeteraDS.Image (not for TX4I);
> Updated CeteraDS.Image;

- src/Kontract/Compression/Level5.cs
- src/text/text_xs/XS.cs
- src/text/text_xs/XsAdapter.cs
Fix Level5 compression methodSize and stream position;
Added XS Save;
> Various updates;

- Kuriimu.sln
- src/archive/archive_hunex/HED.cs
- src/archive/archive_hunex/HEDManager.cs
- src/archive/archive_hunex/HEDSupport.cs
- src/archive/archive_hunex/MRG.cs
- src/archive/archive_hunex/MRGManager.cs
- src/archive/archive_hunex/MRGSupport.cs
- src/archive/archive_hunex/Properties/AssemblyInfo.cs
- src/archive/archive_hunex/archive_hunex.csproj
Add support for loading from the HuneX engine's few archive formats (hed and mrg).
Currently only supports load and extract, saving may be a tad out of my bounds.
I'll also be working further with the HuneX engine for image loading and decompression.
> Added HuneX Load

- src/text/text_t2b/T2B.cs
- src/text/text_t2b/T2bSupport.cs
Clearing file first before start Saving
Adding location(coordinates) of type = 0 entries to avoid misplacing of offset values
> T2B Saving issue fix (Hopefully)

- src/game/game_shin_megami_tensei_iv/Handler.cs
- src/text/text_mbm/MBM.cs
>  MBM Byte Perfection achieved

- src/Kukkii/Converter.cs
This is only export for now, if you like it, we can apply it to import, too
> Batch export/import in threads to make use of all cores

- src/archive/archive_spc/archive_spc.csproj
Found this typo while doing work on case sensitivity issues.
> Fix 'Kruiimu' typo

- src/image/image_g1t/G1TSupport.cs
Improved G1T image plugin compatibility. (More image formats supported)
> Modified G1TSupport.cs

- src/text/text_msbt/MSBT.cs
- src/text/text_msbt/MsbtAdapter.cs
- src/text/text_msbt/MsbtSupport.cs
MSBT files without LBL1 use the NLI1 section to link each String to a global ID.
> Improved msbt support without LBL1.

- src/archive/archive_nintendo/GAR.cs
> Ever Oasis

- src/game/game_rocket_slime_3ds/Handler.cs
still probably not perfect but I haven't had any issues with this yet
> Fixed the RS plugin's battle scene. It's now more accurate.

- src/image/image_g1t/G1TSupport.cs
> G1TSupport: Add 0x3C and 0x45 image formats

- src/text/text_papa/PAPA.cs
- src/text/text_papa/PApaAdapter.cs
Resolved error on PAPA file. (#608)
USA version of PAPA file is a bit different between JPN version of PAPA file.
```python
Offset  Size                        Info                    Hex
0x00    ascii                       Magic stamp [PAPA]      50 41 50 41
0x04    0x08                        Unknown                  00 00 00 00 0C 00 00 00  
0x0C    0x04                        Size of header (0)
0x10    0x04                        Count of subfile
0x14    0x04 * (Count of subfile)   Array of *block* offset
(0) Size of header + 0x0B = First block offset
On a block offset..
Offset      Size        Info                                            Hex
0x00        0x04        block size
0x04        0x04        0x03                                03 00 00 00
0x08        0x04        Offset of …
```
> Fix PAPA file plugin (#608)
